# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c7216088ee3dade618e0589af6ac2741b0da065fe99b3a3dbba7756c5ee228178ff6909b5953b74613d7d47b840105acf387b58366871000a5291a96205dd5c2

test:
  secret_key_base: f2ddeb3689c7cef0e2eb3d0f0c8b37604a15b1536ede6127fd6c404cbe6bcec0ab3991cb7fdd252a02b61120ab5f8c66dc69bbb303c24ecb6ae7701c04b4a583

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
